export const TOKEN_REQUEST = "TOKEN_REQUEST";
export const TOKEN_SUCCESS = "TOKEN_SUCCESS";
export const TOKEN_FAILURE = "TOKEN_FAILURE";

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const FETCH_INVESTOR_REQUEST = 'FETCH_INVESTOR_REQUEST';
export const FETCH_INVESTOR_SUCCESS = 'FETCH_INVESTOR_SUCCESS';
export const FETCH_INVESTOR_FAILURE = 'FETCH_INVESTOR_FAILURE';

export const FETCH_INVESTORS_REQUEST = 'FETCH_INVESTORS_REQUEST';
export const FETCH_INVESTORS_SUCCESS = 'FETCH_INVESTORS_SUCCESS';
export const FETCH_INVESTORS_FAILURE = 'FETCH_INVESTORS_FAILURE';

export const FETCH_INVESTOR_ACC_REQUEST = 'FETCH_INVESTOR_ACC_REQUEST';
export const FETCH_INVESTOR_ACC_SUCCESS = 'FETCH_INVESTOR_ACC_SUCCESS';
export const FETCH_INVESTOR_ACC_FAILURE = 'FETCH_INVESTOR_ACC_FAILURE';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE';

export const FETCH_ACADEMY_REQUEST = 'FETCH_ACADEMY_REQUEST';
export const FETCH_ACADEMY_SUCCESS = 'FETCH_ACADEMY_SUCCESS';
export const FETCH_ACADEMY_FAILURE = 'FETCH_ACADEMY_FAILURE';

export const RESET_STATE = 'RESET_STATE';

export const FETCH_IMAGES_REQUEST = 'FETCH_IMAGES_REQUEST';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';
